### ISSUE TITLE
Arch: DBus Module not found, although it is installed

### ISSUE THREAD

**Issue by ElePhontitis** [erpalma/throttled#114]
I get following Exception when running the tool with the  `--monitor` param:

```
Traceback (most recent call last):
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 6, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

```

I installed both, the general dbus package and python-dbus. Running on Arch and python 3.7.3.

Do you have any idea why this might happen?

**Comment by ElePhontitis** [comment]
If anybody gets the same problem:

I got rid of the Dbus problem by installing `dbus-python` via `pip install dbus-python`
After that I was prompted this exception:

```
Traceback (most recent call last):
File "lenovo-fix.py", line 18, in
from gi.repository import GLib
ImportError: No module named gi.repository

```
After that I changed the first line of the script to ` #!/usr/bin/python` and now it is working. It might was a problem with the various python versions I use and manage via asdf.
